### PR TITLE
Update audit-logging.adoc

### PR DESCRIPTION
**Pull request by nicolasgnr**
Removing invalid audit log event in Exchange documentation. There are no audit log events of read-only operations in Exchange. We will investigate why this event reached the documentation.

### CODE REVIEW

**Review by LucasLudueno — DISMISSED** [review]

**Comment by wwarner-salesforce** [comment]
Looks like the info came from this docs issue, this PR, and originally from this Google doc. Let me know if I can help further.
https://www.mulesoft.org/jira/browse/DOCS-9519
https://github.com/mulesoft/docs-access-management/pull/111
https://docs.google.com/document/d/1mfnpuoMe32Qbb9WDR9h6ThoTQwM3v7DEkhlMnyWAG_A/

**Comment by wwarner-salesforce** [comment]
Based on discussion with Nico Mouso and Tim Daly in Slack channel support-exchange, 'Create a managed tag' and 'Delete a managed tag' are not logged events and should be removed. Making that change now.

**Comment by wwarner-salesforce** [comment]
Done. @nicolasgnr this is another difference between the Google doc and the actual behavior. Would you please review https://docs.mulesoft.com/access-management/audit-logging#exchange and confirm that these are the only changes needed?

**Comment by wwarner-salesforce** [comment]
Lucas found that managed tag create and delete are in logs-- updating.

**Review by LucasLudueno — DISMISSED** [review]

**Review by LucasLudueno — APPROVED** [review]

**Review by sarathecoubian — APPROVED** [review]

**Pull request merged**
