### PR TITLE
[CS-5047] Dropped support for OpenAM 11, 12, 13, only 14 is supported.

### PR DESCRIPTION
**Pull request by wpoch**
https://www.mulesoft.org/jira/browse/CS-5047

### CODE REVIEW

**Review by cmordue — CHANGES_REQUESTED** [review]
please also include updates to:
* https://github.com/mulesoft/docs-access-management/blob/b1f09fa9b6ead350ce3a07efbe2d13a6625344ee/modules/ROOT/pages/conf-openid-connect-task.adoc (should update links to OpenAM 14 documentation)
* https://github.com/mulesoft/docs-access-management/blob/e794fbd4e665ddf94b9c43300697c45faf3bb1ad/modules/ROOT/pages/configure-client-management-openid-task.adoc (should update links to OpenAM 14 documentation)
* https://github.com/mulesoft/docs-access-management/blob/8afeb1fff292dd1d5cc7b8bd35200ab67fce5ab4/modules/ROOT/pages/managing-api-clients.adoc (update version to 14).
* https://github.com/mulesoft/docs-access-management/blob/8afeb1fff292dd1d5cc7b8bd35200ab67fce5ab4/modules/ROOT/pages/external-identity.adoc (remove versions 11 & 12).

**Comment by wpoch** [comment]
Updated the versions in: https://github.com/mulesoft/docs-access-management/pull/26/commits/c8a450f786c973ef176b602c25789dc6a74883b4

Regarding the documentation links I left the existing ones which are the latest ones ¯\_(ツ)_/¯ 

image

image

**Review by cmordue — COMMENTED** [review]
Technically we should call this Forge Rock Access Management 5. OpenAM 14 was renamed to that. See: https://forum.forgerock.com/2017/04/whats-new-forgerock-access-management-5/
So the correct docs to link to are to Access Management 5

**Comment by wpoch** [comment]
Thanks @cmordue  for the clarification, I just updated the links with the AM 5 ones.

**Review by cmordue — APPROVED** [review]
LGTM
Thanks, Walter!

**Pull request merged**
